### PR TITLE
Change pack version in Hello.cproject.yml

### PR DESCRIPTION
**Pull request by RonanSynnottArm**
Change pack version to 1.4.0

### CODE REVIEW

**Comment by jkrech** [comment]
@RonanSynnottArm could you please elaborate why you suggest to revert to version 1.4.0 of the BSP rather than fixing it to the currently latest version 1.5.0 released in Feb. 2024? Is there something wrong with that version?

**Comment by RonanSynnottArm** [comment]
Is 1.5.0 available? The build fails to find this for me.
Also verified in MDK Pack manager.

**Comment by jkrech** [comment]
https://www.keil.arm.com/packs/v2m_mps3_sse_300_bsp-arm/versions/
Have you run the check for updates recently in the MDK PackInstaller 
or for CMSIS-Toolbox: `cpackget update-index` ?

**Comment by RonanSynnottArm** [comment]
Apologies. It is now updated.
I close this PR.

**Pull request closed without merging**
